version: "3"
services:
    frontend:
        container_name: pokemon_app_frontend
        build:
            context: ./client
            dockerfile: Dockerfile
        image: pokemon_app/pokemon_app_frontend
        ports:
            - "3000:3000"
        volumes:
            - ./client:/usr/src/app
    backend:
        container_name: pokemon_app_server
        build:
            context: ./
            dockerfile: Dockerfile
        image: pokemon_app/pokemon_app_server
        ports:
            - "3001:3001"
        volumes:
            - ./:/usr/src/app